import React, { useContext } from "react";
import classNames from "./earningOpportunity.module.scss";

//assets

import arrowInCircleIcon from "../../../assets/images/icons/arrowincircle.svg";

import web3brokerIcon from "../../../assets/images/logos/web3broker.svg";
import web3transcriptIcon from "../../../assets/images/logos/transcript.svg";
import web3commercialsIcon from "../../../assets/images/logos/web3commercials.svg";
import { GlobalContex } from "../../../globalContext";
import { useHistory } from "react-router-dom";

const EarningOpportunity = () => {
  const history = useHistory();
  const { setRegisterUser, setStatsOpened } = useContext(GlobalContex);
  const allOpportunities = [
    {
      title: "Web3 Brokers",
      desc: "Create your digital Web3 storefront with all the products, projects, and brands you want to promote. Get paid each time someone buys from your brokerage.",
      logo: web3brokerIcon,
    },
    {
      title: "Web3 Transcript",
      desc: "Get paid to learn about Web3. Earn points each time you complete an article video and answer a question. Your points are saved to your transcript and are convertible to crypto.",
      logo: web3transcriptIcon,
    },
    {
      title: "Web3 Commercials",
      desc: "Web3 brands want to pay you to learn about their products. By watching Web3 Commercials, you get a direct cut out of the advertising revenue generated by Web3Today.",
      logo: web3commercialsIcon,
    },
  ];
  return (
    <div className={classNames.earningOpportunity}>
      <div className={classNames.header}>
        <span>Earning Opportunities</span>
        <span
          onClick={() => {
            setStatsOpened(false);
            setRegisterUser("loginclosed");
          }}
        >
          X
        </span>
      </div>
      <div className={classNames.cardsParent}>
        {allOpportunities?.length > 0 &&
          allOpportunities?.map(({ title, desc, logo }, index) => {
            return (
              <div
                className={classNames.eachCard}
                key={title + index}
                onClick={() => {
                  if (title == "Web3 Transcript") {
                    setRegisterUser("");
                  } else if (
                    title == "Web3 Commercials" ||
                    title == "Web3 Brokers"
                  ) {
                    // history.push("/earn/ads");
                    window.open("https://app.web3today.io/", "_blank");
                  }
                }}
              >
                <div className={classNames.title}>{title}</div>
                <div className={classNames.desc}>{desc}</div>
                <div className={classNames.btnParent}>
                  <div className={classNames.arrowBtn}>
                    <span>See More</span>
                    <img src={arrowInCircleIcon} alt="arrowInCircleIcon" />
                  </div>
                  <img src={logo} alt={title} />
                </div>
              </div>
            );
          })}
      </div>
    </div>
  );
};

export default EarningOpportunity;
